import os

# ========= API & DATA CONFIGURATION ========= #

# API CREDENTIALS
ALPACA_KEY = os.getenv("ALPACA_KEY")
ALPACA_SECRET = os.getenv("ALPACA_SECRET")

# API URLS
OPTIONS_URL = "wss://stream.data.alpaca.markets/v1beta1/indicative"

# Bot webhook URL
CALL_WEBHOOK = os.getenv("CALL_WEBHOOK")
PUT_WEBHOOK = os.getenv("PUT_WEBHOOK")
# ========= PARAMETERS ========= #

# DATA PARAMETERS
SYMBOL = "SPY"
START = "T09:30:00-05:00"
END = "T15:59:00-05:00"
INDICATOR_LOOKBACK = 3

# EMA PARAMETERS
EMA_SHORT_PERIOD = 5
EMA_LONG_PERIOD = 14

# HULL MA PARAMETERS
HMA_PERIOD = 9

#SUPERTREND PARAMETERS
SUPERTREND_ATR_PERIOD = 2
SUPERTREND_MULTIPLIER = 2.2

#MACD PARAMETERS
MACD_FAST_LENGTH = 12
MACD_SLOW_LENGTH = 26
MACD_SIGNAL_LENGTH = 9

# RSI PARAMETERS
RSI_PERIOD = 14
RSI_LONG = 45
RSI_SHORT = 55

#SELLING PARAMETERS
TRAILING_SL = 0.10  # 10% trailing stop loss
HARD_SL = 0.15      # 15% hard stop loss
TIME_LIMIT = 420    # 7 minutes time limit
